
import TurtleGraphics.*;
import BreezySwing.*;
import java.awt.Color;
import javax.swing.JOptionPane;

public class ShapeMaker extends javax.swing.JFrame {

    private int XPos, YPos, radius, pwidth, width, height;
    AbstractShape s;
    Pen p;
    SketchPadWindow w = new SketchPadWindow(300, 340);

    public ShapeMaker() {
        initComponents();
        w.setLocation(270, 26);
        s = new Circle(XPos, YPos, radius);
        p = new StandardPen(w);
        pwidth = 1;
        choice.add("Select Shape");
        choice.add("Circle");
        choice.add("Rectangle");
        penchoice.add("Standard Pen");
        penchoice.add("Rainbow Pen");
        point.add("1");
        point.add("2");
        point.add("3");
    }

    private void erase() {
        p = new StandardPen(w);
        p.setColor(Color.white);
        p.setWidth(1000);
        s.draw(p);
        p.setWidth(pwidth);
    }

    private void text() {
        txtarea.setText("");
        txtarea.setText(s.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        choice = new java.awt.Choice();
        XPostxt = new javax.swing.JTextField();
        YPostxt = new javax.swing.JTextField();
        widthtxt = new javax.swing.JTextField();
        heighttxt = new javax.swing.JTextField();
        radiustxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        btnrefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        penchoice = new java.awt.Choice();
        jLabel8 = new javax.swing.JLabel();
        pentxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stretchtxt = new javax.swing.JTextField();
        point = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Shape:");

        jLabel2.setText("X Pos:");

        jLabel3.setText("Y Pos:");

        jLabel4.setText("Width:");

        jLabel5.setText("Height:");

        jLabel6.setText("Radius:");

        choice.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                choiceComponentShown(evt);
            }
        });
        choice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceItemStateChanged(evt);
            }
        });
        choice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                choiceFocusGained(evt);
            }
        });

        heighttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heighttxtActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jLabel7.setText("Pen:");

        penchoice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                penchoiceItemStateChanged(evt);
            }
        });

        jLabel8.setText("Pen Width:");

        jLabel9.setText("Point #:");

        jLabel10.setText("Stretch:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiustxt)
                                    .addComponent(point, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(25, 25, 25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(23, 23, 23)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(widthtxt)
                                    .addComponent(XPostxt)
                                    .addComponent(choice, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pentxt, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(YPostxt)
                            .addComponent(heighttxt)
                            .addComponent(penchoice, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(stretchtxt))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(choice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(penchoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(XPostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YPostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(widthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radiustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(pentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(stretchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnrefresh)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choiceComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_choiceComponentShown

    }//GEN-LAST:event_choiceComponentShown

    private void choiceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_choiceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceFocusGained

    private void choiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceItemStateChanged
        radiustxt.setEnabled(true);
        heighttxt.setEnabled(true);
        widthtxt.setEnabled(true);
        XPostxt.setEnabled(true);
        YPostxt.setEnabled(true);
        point.setEnabled(true);
        stretchtxt.setEditable(true);
        if ("Circle".equals(this.getChoice())) {
            heighttxt.setEnabled(false);
            widthtxt.setEnabled(false);
            point.setEnabled(false);
            stretchtxt.setEnabled(false);
            if ("".equals(XPostxt.getText())) {
                XPostxt.setText("0");
            }
            if ("".equals(YPostxt.getText())) {
                YPostxt.setText("0");
            }
            if ("".equals(radiustxt.getText())) {
                radiustxt.setText("100");
            }
            if ("".equals(pentxt.getText())) {
                pentxt.setText("1");
            }
            text();

        }
        if ("Rectangle".equals(this.getChoice())) {
            radiustxt.setEnabled(false);
            point.setEnabled(false);
            stretchtxt.setEnabled(false);
            if ("".equals(XPostxt.getText())) {
                XPostxt.setText("0");
            }
            if ("".equals(YPostxt.getText())) {
                YPostxt.setText("0");
            }
            if ("".equals(heighttxt.getText())) {
                heighttxt.setText("100");
            }
            if ("".equals(widthtxt.getText())) {
                widthtxt.setText("100");
            }
            if ("".equals(pentxt.getText())) {
                pentxt.setText("1");
            }
            text();
        }

    }//GEN-LAST:event_choiceItemStateChanged

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        XPos = Integer.parseInt(XPostxt.getText());
        YPos = Integer.parseInt(YPostxt.getText());
        if ("Rectangle".equals(this.getChoice())) {
            width = Integer.parseInt(widthtxt.getText());
            height = Integer.parseInt(heighttxt.getText());
        }
        if ("Circle".equals(this.getChoice())) {
            radius = Integer.parseInt(radiustxt.getText());
        }
        erase();
        p.setWidth(pwidth);
        if ("Standard Pen".equals(this.getPen())) {
            p = new StandardPen(w);
        }
        if ("Rainbow Pen".equals(this.getPen())) {
            p = new RainbowPen(w);
        }
        if ("Circle".equals(this.getChoice())) {
            s = new Circle(XPos, YPos, radius);
        }
        if ("Rectangle".equals(this.getChoice())) {
            s = new Rectangle(XPos, YPos, width, height);
        }
        pwidth = Integer.parseInt(pentxt.getText());
        p.setWidth(pwidth);
        s.draw(p);
        text();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void heighttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heighttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heighttxtActionPerformed

    private void penchoiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_penchoiceItemStateChanged
        if ("Standard Pen".equals(this.getPen())) {
            p = new StandardPen(w);
        }
        if ("Rainbow Pen".equals(this.getPen())) {
            p = new RainbowPen(w);
        }
    }//GEN-LAST:event_penchoiceItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShapeMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeMaker().setVisible(true);
            }
        });
    }

    public String getChoice() {
        String selection;
        selection = choice.getSelectedItem();
        return selection;
    }

    public String getPen() {
        String selection;
        selection = penchoice.getSelectedItem();
        return selection;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField XPostxt;
    private javax.swing.JTextField YPostxt;
    private javax.swing.JButton btnrefresh;
    private java.awt.Choice choice;
    private javax.swing.JTextField heighttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Choice penchoice;
    private javax.swing.JTextField pentxt;
    private java.awt.Choice point;
    private javax.swing.JTextField radiustxt;
    private javax.swing.JTextField stretchtxt;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField widthtxt;
    // End of variables declaration//GEN-END:variables
}
